project:
  type: website

website:
  title: "High Performance Computing Facility, IIT Kharagpur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



