project:
  type: website

website:
  title: "HPC Facility, IIT Kharagpur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - gettingStarted.qmd
      - guides.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



